/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RfoRouteImport } from './routes/rfo'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ChamadosRouteImport } from './routes/chamados'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotificacoesPreferenciasRouteImport } from './routes/notificacoes.preferencias'
import { Route as DiagnosticoServerFunctionsRouteImport } from './routes/diagnostico.server-functions'
import { Route as ConfiguracoesSlaRouteImport } from './routes/configuracoes.sla'
import { Route as ClientesIdRouteImport } from './routes/clientes_.$id'
import { Route as ApiPublicDiagRouteImport } from './routes/api/public/_diag'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RfoRoute = RfoRouteImport.update({
  id: '/rfo',
  path: '/rfo',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamadosRoute = ChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesPreferenciasRoute =
  NotificacoesPreferenciasRouteImport.update({
    id: '/preferencias',
    path: '/preferencias',
    getParentRoute: () => NotificacoesRoute,
  } as any)
const DiagnosticoServerFunctionsRoute =
  DiagnosticoServerFunctionsRouteImport.update({
    id: '/diagnostico/server-functions',
    path: '/diagnostico/server-functions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConfiguracoesSlaRoute = ConfiguracoesSlaRouteImport.update({
  id: '/configuracoes/sla',
  path: '/configuracoes/sla',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes_/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiagRoute = ApiPublicDiagRouteImport.update({
  id: '/api/public/_diag',
  path: '/api/public',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/rfo': typeof RfoRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/sla': typeof ConfiguracoesSlaRoute
  '/diagnostico/server-functions': typeof DiagnosticoServerFunctionsRoute
  '/notificacoes/preferencias': typeof NotificacoesPreferenciasRoute
  '/api/public': typeof ApiPublicDiagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/rfo': typeof RfoRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/configuracoes/sla': typeof ConfiguracoesSlaRoute
  '/diagnostico/server-functions': typeof DiagnosticoServerFunctionsRoute
  '/notificacoes/preferencias': typeof NotificacoesPreferenciasRoute
  '/api/public': typeof ApiPublicDiagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chamados': typeof ChamadosRoute
  '/clientes': typeof ClientesRoute
  '/dashboard': typeof DashboardRoute
  '/equipamentos': typeof EquipamentosRoute
  '/login': typeof LoginRoute
  '/notificacoes': typeof NotificacoesRouteWithChildren
  '/perfil': typeof PerfilRoute
  '/planos': typeof PlanosRoute
  '/relatorios': typeof RelatoriosRoute
  '/rfo': typeof RfoRoute
  '/usuarios': typeof UsuariosRoute
  '/clientes_/$id': typeof ClientesIdRoute
  '/configuracoes/sla': typeof ConfiguracoesSlaRoute
  '/diagnostico/server-functions': typeof DiagnosticoServerFunctionsRoute
  '/notificacoes/preferencias': typeof NotificacoesPreferenciasRoute
  '/api/public/_diag': typeof ApiPublicDiagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chamados'
    | '/clientes'
    | '/dashboard'
    | '/equipamentos'
    | '/login'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/rfo'
    | '/usuarios'
    | '/clientes/$id'
    | '/configuracoes/sla'
    | '/diagnostico/server-functions'
    | '/notificacoes/preferencias'
    | '/api/public'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chamados'
    | '/clientes'
    | '/dashboard'
    | '/equipamentos'
    | '/login'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/rfo'
    | '/usuarios'
    | '/clientes/$id'
    | '/configuracoes/sla'
    | '/diagnostico/server-functions'
    | '/notificacoes/preferencias'
    | '/api/public'
  id:
    | '__root__'
    | '/'
    | '/chamados'
    | '/clientes'
    | '/dashboard'
    | '/equipamentos'
    | '/login'
    | '/notificacoes'
    | '/perfil'
    | '/planos'
    | '/relatorios'
    | '/rfo'
    | '/usuarios'
    | '/clientes_/$id'
    | '/configuracoes/sla'
    | '/diagnostico/server-functions'
    | '/notificacoes/preferencias'
    | '/api/public/_diag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChamadosRoute: typeof ChamadosRoute
  ClientesRoute: typeof ClientesRoute
  DashboardRoute: typeof DashboardRoute
  EquipamentosRoute: typeof EquipamentosRoute
  LoginRoute: typeof LoginRoute
  NotificacoesRoute: typeof NotificacoesRouteWithChildren
  PerfilRoute: typeof PerfilRoute
  PlanosRoute: typeof PlanosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  RfoRoute: typeof RfoRoute
  UsuariosRoute: typeof UsuariosRoute
  ClientesIdRoute: typeof ClientesIdRoute
  ConfiguracoesSlaRoute: typeof ConfiguracoesSlaRoute
  DiagnosticoServerFunctionsRoute: typeof DiagnosticoServerFunctionsRoute
  ApiPublicDiagRoute: typeof ApiPublicDiagRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfo': {
      id: '/rfo'
      path: '/rfo'
      fullPath: '/rfo'
      preLoaderRoute: typeof RfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamados': {
      id: '/chamados'
      path: '/chamados'
      fullPath: '/chamados'
      preLoaderRoute: typeof ChamadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes/preferencias': {
      id: '/notificacoes/preferencias'
      path: '/preferencias'
      fullPath: '/notificacoes/preferencias'
      preLoaderRoute: typeof NotificacoesPreferenciasRouteImport
      parentRoute: typeof NotificacoesRoute
    }
    '/diagnostico/server-functions': {
      id: '/diagnostico/server-functions'
      path: '/diagnostico/server-functions'
      fullPath: '/diagnostico/server-functions'
      preLoaderRoute: typeof DiagnosticoServerFunctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes/sla': {
      id: '/configuracoes/sla'
      path: '/configuracoes/sla'
      fullPath: '/configuracoes/sla'
      preLoaderRoute: typeof ConfiguracoesSlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes_/$id': {
      id: '/clientes_/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/_diag': {
      id: '/api/public/_diag'
      path: '/api/public'
      fullPath: '/api/public'
      preLoaderRoute: typeof ApiPublicDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NotificacoesRouteChildren {
  NotificacoesPreferenciasRoute: typeof NotificacoesPreferenciasRoute
}

const NotificacoesRouteChildren: NotificacoesRouteChildren = {
  NotificacoesPreferenciasRoute: NotificacoesPreferenciasRoute,
}

const NotificacoesRouteWithChildren = NotificacoesRoute._addFileChildren(
  NotificacoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChamadosRoute: ChamadosRoute,
  ClientesRoute: ClientesRoute,
  DashboardRoute: DashboardRoute,
  EquipamentosRoute: EquipamentosRoute,
  LoginRoute: LoginRoute,
  NotificacoesRoute: NotificacoesRouteWithChildren,
  PerfilRoute: PerfilRoute,
  PlanosRoute: PlanosRoute,
  RelatoriosRoute: RelatoriosRoute,
  RfoRoute: RfoRoute,
  UsuariosRoute: UsuariosRoute,
  ClientesIdRoute: ClientesIdRoute,
  ConfiguracoesSlaRoute: ConfiguracoesSlaRoute,
  DiagnosticoServerFunctionsRoute: DiagnosticoServerFunctionsRoute,
  ApiPublicDiagRoute: ApiPublicDiagRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
